[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Full"
opacity = 0.6
decorations_theme_variant = "Dark"

[font]
normal = { family = "CodeNewRomanNerdFont", style="Regular"}
size = 11
