[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Full"
opacity = 0.9
decorations_theme_variant = "Dark"

[font]
bold = { family = "IosevkaTermSlabNerdFont", style = "Medium" }
size = 11
