# ~/.config/starship.toml

add_newline = false
continuation_prompt = "[▸▹ ](dimmed white)"

format = """[┌──\\(](dimmed blue)$username[@](white)$hostname[\\)-\\[](dimmed blue)$time[\\]-\\[](dimmed blue)$directory[\\]](dimmed blue)\
(\n[│](green)( $python) |( $git_branch$git_commit$git_state))
[└](dimmed blue)$cmd_duration[─](dimmed blue)[\\$ ](bold blue)"""
right_format = '''$battery'''


[python]
format = '[\[$symbol$version\][(\[$virtualenv\])](dimmed red)]($style)'
symbol = ' '
version_format = 'v${raw}'
pyenv_version_name = false

[git_branch]
format = '[\[$symbol$branch\]]($style)'

[git_commit]
format = '[\[commit hash:$hash$tag\]]($style)'
commit_hash_length = 8
only_detached = false
tag_disabled = false
style = "dimmed yellow"

[git_state]
format = '[\[$state( $progress_current of $progress_total)\]]($style)'
style = "dimmed yellow"


[hostname]
ssh_only = false
format = "[$hostname]($style)"
trim_at = "-"
style = "bold blue"
disabled = false

[username]
show_always = true
style_root = "bg:#9A348E"
format = '[$user]($style)'
disabled = false
style_user = "bold blue"

[time]
disabled = false
format = "[🕙$time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic white"


[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 100
style = "bold red"

[character]
error_symbol = "[✖](bold red) "

[cmd_duration]
min_time = 10_000 # Show command duration over 10,000 milliseconds (=10 sec)
style = "dimmed red"
format = '[\(took $duration\)]($style)'

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style)"
style = "white"





[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨 ×${count} "
behind = "🐢 ×${count} "
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count} "
untracked = "🛤️  ×${count} "
stashed = "📦 "
modified = "📝 ×${count} "
staged = "🗃️  ×${count} "
renamed = "📛 ×${count} "
deleted = "🗑️  ×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"


[julia]
format = "[$symbol$version]($style) "
symbol = "ஃ "
style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[package]
disabled = true



[rust]
format = "[$symbol$version]($style) "
style = "bold green"



[typst]
format = "[$symbol($version)]($style)"
style = "bold #239dae"

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false



[nodejs]
format = "via [🤖 $version](bold green) "
